name: rusty_ffi_dart
description: Call Rust code from Dart
version: 1.0.0
homepage: https://github.com/linux-china/rusty_ffi_dart
author: linux_china <libing.chen@gmail.com>

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
