name: rusty_ffi_dart
description: Call Rust code from Dart
version: 1.0.0
homepage: https://github.com/linux-china/rusty_ffi_dart
author: linux_china <libing.chen@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
